"""Build the Moss attorney-routing index from the curated law_firms dataset."""

from __future__ import annotations

import argparse
import asyncio
import csv
import json
import os
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Final

from dotenv import load_dotenv
from moss import DocumentInfo, MossClient

DEFAULT_INDEX_NAME: Final[str] = "jailcall-lawyers"
DEFAULT_MODEL_ID: Final[str] = "moss-minilm"
ROOT: Final[Path] = Path(__file__).resolve().parent.parent
LAW_FIRMS_DIR: Final[Path] = ROOT / "law_firms"
DEFAULT_PREVIEW_PATH: Final[Path] = ROOT / "evals" / "last_run" / "moss_index_documents.jsonl"
MAX_CHARS_PER_CHUNK: Final[int] = 4_500
CHUNK_OVERLAP: Final[int] = 450
HEADER_SPLIT_PARTS: Final[int] = 2


@dataclass(frozen=True)
class IndexDocument:
    """One Moss document with firm dispatch metadata attached."""

    id: str
    text: str
    metadata: dict[str, str]


def clean(value: object) -> str:
    """Normalize text for embedding and metadata."""
    text = "" if value is None else str(value)
    return re.sub(r"\s+", " ", text.replace("\t", " ")).strip()


def slugify(value: str) -> str:
    """Return a stable id fragment."""
    value = value.lower()
    value = re.sub(r"[^a-z0-9]+", "-", value)
    return value.strip("-") or "chunk"


def read_profiles(law_firms_dir: Path) -> list[dict[str, str]]:
    """Read the firm routing table generated by law_firms/curate_corpus.py."""
    path = law_firms_dir / "firm_profiles.tsv"
    with path.open(newline="", encoding="utf-8") as handle:
        return [
            {clean(key): clean(value) for key, value in row.items()}
            for row in csv.DictReader(handle, delimiter="\t")
        ]


def read_cases(law_firms_dir: Path) -> dict[str, list[dict[str, str]]]:
    """Read representative case rows by firm id."""
    path = law_firms_dir / "cases.tsv"
    if not path.exists():
        return {}
    cases_by_firm: dict[str, list[dict[str, str]]] = {}
    with path.open(newline="", encoding="utf-8") as handle:
        for row in csv.DictReader(handle, delimiter="\t"):
            case = {clean(key): clean(value) for key, value in row.items()}
            short_name = case.get("SHORT_NAME", "")
            if short_name:
                cases_by_firm.setdefault(short_name, []).append(case)
    return cases_by_firm


def parse_text_header(text: str, key: str) -> str:
    """Extract a header line from a normalized site_text file."""
    prefix = f"{key}:"
    for line in text.splitlines()[:8]:
        if line.startswith(prefix):
            return clean(line[len(prefix) :])
    return ""


def strip_text_headers(text: str) -> str:
    """Drop scraper headers so chunks focus on website language."""
    parts = text.split("\n\n", 1)
    return clean(parts[1] if len(parts) == HEADER_SPLIT_PARTS else text)


def chunk_text(text: str, *, max_chars: int = MAX_CHARS_PER_CHUNK) -> list[str]:
    """Split normalized text into overlapping chunks."""
    text = clean(text)
    if not text:
        return []
    if len(text) <= max_chars:
        return [text]

    chunks: list[str] = []
    start = 0
    while start < len(text):
        end = min(start + max_chars, len(text))
        if end < len(text):
            boundary = max(
                text.rfind(". ", start, end),
                text.rfind("? ", start, end),
                text.rfind("! ", start, end),
            )
            if boundary > start + max_chars // 2:
                end = boundary + 1
        chunk = clean(text[start:end])
        if chunk:
            chunks.append(chunk)
        if end >= len(text):
            break
        start = max(end - CHUNK_OVERLAP, 0)
    return chunks


def base_metadata(profile: dict[str, str]) -> dict[str, str]:
    """Metadata returned by moss_find_lawyers for every matching chunk."""
    return {
        "firm_id": profile["SHORT_NAME"],
        "name": profile["NAME"],
        "short_name": profile["SHORT_NAME"],
        "website": profile["WEBSITE"],
        "phone": profile["PHONE"],
        "email": profile["EMAIL"],
        "intake_url": profile["INTAKE_URL"],
        "counties": profile["COUNTIES"],
        "charge_tags": profile["PRIMARY_CHARGE_TAGS"],
        "case_count": profile["CASE_COUNT"],
    }


def routing_header(profile: dict[str, str]) -> str:
    """Firm-level context prepended to every chunk."""
    return "\n".join(
        [
            "JailCall attorney routing document.",
            (
                "Use this document to match a caller's criminal charge category "
                "to a reachable Bay Area criminal defense firm."
            ),
            f"Firm: {profile['NAME']}",
            f"Counties served: {profile['COUNTIES']}",
            f"Charge categories: {profile['PRIMARY_CHARGE_TAGS']}",
            f"Dispatch phone: {profile['PHONE']}",
            f"Dispatch email: {profile['EMAIL']}" if profile["EMAIL"] else "Dispatch email:",
            (
                f"Dispatch form: {profile['INTAKE_URL']}"
                if profile["INTAKE_URL"]
                else "Dispatch form:"
            ),
            "",
        ]
    )


def profile_document(profile: dict[str, str]) -> IndexDocument:
    """Create the firm profile routing doc."""
    metadata = {
        **base_metadata(profile),
        "source_type": "firm_profile",
        "source_path": f"{profile['SHORT_NAME']}/firm.txt",
        "source_url": profile["WEBSITE"],
        "chunk": "0",
    }
    text = "\n".join(
        [
            routing_header(profile),
            "Structured routing profile:",
            profile["PROFILE_TEXT"],
            f"Representative cases: {profile['REPRESENTATIVE_CASES']}",
            f"Source URLs: {profile['SOURCE_URLS']}",
        ]
    )
    return IndexDocument(
        id=f"{profile['SHORT_NAME']}:profile",
        text=clean(text),
        metadata=metadata,
    )


def site_documents(profile: dict[str, str], law_firms_dir: Path) -> list[IndexDocument]:
    """Create raw website text chunks for one firm."""
    short_name = profile["SHORT_NAME"]
    site_text_dir = law_firms_dir / short_name / "site_text"
    docs: list[IndexDocument] = []
    for path in sorted(site_text_dir.glob("*.txt")):
        if path.name == "errors.txt":
            continue
        raw_text = path.read_text(encoding="utf-8", errors="ignore")
        source_url = parse_text_header(raw_text, "URL")
        title = parse_text_header(raw_text, "Title")
        body = strip_text_headers(raw_text)
        for index, chunk in enumerate(chunk_text(body), start=1):
            metadata = {
                **base_metadata(profile),
                "source_type": "site_text",
                "source_path": str(path.relative_to(law_firms_dir)),
                "source_url": source_url,
                "source_title": title,
                "chunk": str(index),
            }
            text = "\n".join(
                [
                    routing_header(profile),
                    "Normalized firm website text:",
                    f"Page title: {title}",
                    f"Page URL: {source_url}",
                    "",
                    chunk,
                ]
            )
            docs.append(
                IndexDocument(
                    id=f"{short_name}:site:{slugify(path.stem)}:{index}",
                    text=clean(text),
                    metadata=metadata,
                )
            )
    return docs


def case_documents(
    profile: dict[str, str],
    cases: list[dict[str, str]],
) -> list[IndexDocument]:
    """Create representative case docs for charge-specific routing."""
    short_name = profile["SHORT_NAME"]
    docs: list[IndexDocument] = []
    for index, case in enumerate(cases, start=1):
        metadata = {
            **base_metadata(profile),
            "source_type": "representative_case",
            "source_path": case.get("CASE_PATH", ""),
            "source_url": case.get("SOURCE_URL", ""),
            "case_name": case.get("CASE_NAME", ""),
            "offense_tags": case.get("OFFENSE_TAGS", ""),
            "chunk": str(index),
        }
        text = "\n".join(
            [
                routing_header(profile),
                "Representative criminal case signal:",
                f"Case name: {case.get('CASE_NAME', '')}",
                f"Offense tags: {case.get('OFFENSE_TAGS', '')}",
                f"Actual charges: {case.get('ACTUAL_CHARGES', '')}",
                f"Description: {case.get('DESCRIPTION', '')}",
                f"Court: {case.get('COURT', '')}",
                f"Attorney listed: {case.get('ATTORNEY', '')}",
            ]
        )
        docs.append(
            IndexDocument(
                id=f"{short_name}:case:{index}:{slugify(case.get('CASE_NAME', 'case'))}",
                text=clean(text),
                metadata=metadata,
            )
        )
    return docs


def build_documents(law_firms_dir: Path = LAW_FIRMS_DIR) -> list[IndexDocument]:
    """Build all Moss documents from firm profiles, site text, and case signals."""
    profiles = read_profiles(law_firms_dir)
    cases_by_firm = read_cases(law_firms_dir)
    docs: list[IndexDocument] = []
    for profile in profiles:
        short_name = profile["SHORT_NAME"]
        site_docs = site_documents(profile, law_firms_dir)
        if not site_docs:
            continue
        docs.append(profile_document(profile))
        docs.extend(site_docs)
        docs.extend(case_documents(profile, cases_by_firm.get(short_name, [])))
    return docs


def write_preview(path: Path, docs: list[IndexDocument]) -> None:
    """Write the exact JSON payload shape used for Moss docs."""
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as handle:
        for doc in docs:
            handle.write(
                json.dumps(
                    {"id": doc.id, "text": doc.text, "metadata": doc.metadata},
                    ensure_ascii=True,
                    sort_keys=True,
                )
                + "\n"
            )


async def push_to_moss(
    *,
    docs: list[IndexDocument],
    index_name: str,
    model_id: str,
) -> None:
    """Create and load the Moss index."""
    project_id = os.environ.get("MOSS_PROJECT_ID")
    project_key = os.environ.get("MOSS_PROJECT_KEY")
    if not project_id or not project_key:
        msg = "MOSS_PROJECT_ID and MOSS_PROJECT_KEY must be set to push the index."
        raise RuntimeError(msg)

    moss_docs: list[Any] = [
        DocumentInfo(id=doc.id, text=doc.text, metadata=doc.metadata) for doc in docs
    ]
    client = MossClient(project_id, project_key)
    await client.delete_index(index_name)
    await client.create_index(index_name, moss_docs, model_id)
    await client.load_index(index_name)


def summarize(docs: list[IndexDocument]) -> dict[str, int]:
    """Return build stats for stdout and validation."""
    firms = {doc.metadata["firm_id"] for doc in docs}
    site_docs = [doc for doc in docs if doc.metadata.get("source_type") == "site_text"]
    case_docs = [doc for doc in docs if doc.metadata.get("source_type") == "representative_case"]
    profile_docs = [doc for doc in docs if doc.metadata.get("source_type") == "firm_profile"]
    return {
        "firms": len(firms),
        "docs": len(docs),
        "profile_docs": len(profile_docs),
        "site_text_docs": len(site_docs),
        "case_docs": len(case_docs),
    }


async def async_main() -> None:
    """CLI entry point."""
    _ = load_dotenv()
    parser = argparse.ArgumentParser()
    parser.add_argument("--law-firms-dir", type=Path, default=LAW_FIRMS_DIR)
    parser.add_argument(
        "--index-name",
        default=os.environ.get("MOSS_INDEX_NAME", DEFAULT_INDEX_NAME),
    )
    parser.add_argument("--model-id", default=DEFAULT_MODEL_ID)
    parser.add_argument("--push", action="store_true")
    parser.add_argument("--preview-path", type=Path, default=DEFAULT_PREVIEW_PATH)
    parser.add_argument("--no-preview", action="store_true")
    args = parser.parse_args()

    docs = build_documents(args.law_firms_dir)
    stats = summarize(docs)
    print(
        "built"
        + f" firms={stats['firms']} docs={stats['docs']}"
        + f" profile_docs={stats['profile_docs']} site_text_docs={stats['site_text_docs']}"
        + f" case_docs={stats['case_docs']}",
    )

    if not args.no_preview:
        write_preview(args.preview_path, docs)
        print(f"wrote preview={args.preview_path}")

    if args.push:
        try:
            await push_to_moss(docs=docs, index_name=args.index_name, model_id=args.model_id)
        except RuntimeError as exc:
            raise SystemExit(f"moss_push_failed: {exc}") from exc
        print(f"pushed index={args.index_name} model={args.model_id}")
    else:
        print("dry_run=true; pass --push to create/load the Moss index")


def main() -> None:
    """Run the async CLI."""
    asyncio.run(async_main())


if __name__ == "__main__":
    main()
